<a href="https://colab.research.google.com/github/RatchanonPa/bsc_dpdm24/blob/main/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 3

จาก Data Reduced_Marketbasket
1. วิเคราะห์พฤติกรรมผู้บริโภค (groupby customer id) แต่ละทวีป
2. คิดเอง

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=0d01a3cf03acdb2b44f17cd8b468e4fd11b1d717434005cda95afa334655104b
  Stored in directory: /root/.cache/pip/wheels/77/3d/a6/d317a6fb32be58a602b1e8c6b5d6f31f79322da554cad2a5ea
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
from apyori import apriori

## import data

In [ ]:
import pandas as pd
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/bsc_dpdm24_data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data = pd.read_csv(os.path.join(path,'reduced_marketbasket.csv'),encoding='latin-1')

In [ ]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

In [ ]:
set(data['Country'])

{'Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EIRE',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'RSA',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified'}

In [ ]:
len(set(data['Country']))

38

## Prepare Data
> ต้องการเพียงข้อมูลที่เป็น เดือน/วัน/ปี จาก Column InvoiceDate

### แยก เดือน/วัน/ปี ออกจาก เวลา

In [ ]:
data['InvoiceDate'][0].split()[0]

'12/01/2010'

In [ ]:
date = []
for i in range(len(data['InvoiceDate'])):
  x = data['InvoiceDate'][i].split()[0]
  date.append(x)
#set(L)

In [ ]:
# ลองทดสอบดู
date[0].split('/')

['12', '01', '2010']

### แยก เดือน/วัน/ปี ออกจากกัน

In [ ]:
day =[]
month =[]
year =[]
for i in range(len(data['InvoiceDate'])):
  x = date[i].split('/')[0]
  y = date[i].split('/')[1]
  z = date[i].split('/')[2]
  month.append(x)
  day.append(y)
  year.append(z)

### นำ data ใหม่ไปใช้

In [ ]:
data_test_nonclean = data

In [ ]:
data_test_nonclean['date'] = date
data_test_nonclean['day'] = day
data_test_nonclean['month'] = month
data_test_nonclean['year'] = year

# data_test_nonclean >>> ข้อมูลยังไม่อยู่ในมาตรฐานเดียวกัน

In [ ]:
set(data_test_nonclean['date'])

{'01/04/2011',
 '01/05/2011',
 '01/06/2011',
 '01/07/2011',
 '01/09/2011',
 '01/10/2011',
 '01/11/2011',
 '01/12/2011',
 '02/01/2011',
 '02/02/2011',
 '02/03/2011',
 '02/04/2011',
 '02/06/2011',
 '02/07/2011',
 '02/08/2011',
 '02/09/2011',
 '02/10/2011',
 '02/11/2011',
 '03/01/2011',
 '03/02/2011',
 '03/03/2011',
 '03/04/2011',
 '03/06/2011',
 '03/07/2011',
 '03/08/2011',
 '03/09/2011',
 '03/10/2011',
 '03/11/2011',
 '04/01/2011',
 '04/03/2011',
 '04/04/2011',
 '04/05/2011',
 '04/06/2011',
 '04/07/2011',
 '04/08/2011',
 '04/10/2011',
 '04/11/2011',
 '04/12/2011',
 '05/01/2011',
 '05/03/2011',
 '05/04/2011',
 '05/05/2011',
 '05/06/2011',
 '05/08/2011',
 '05/09/2011',
 '05/10/2011',
 '05/11/2011',
 '05/12/2011',
 '06/01/2011',
 '06/02/2011',
 '06/03/2011',
 '06/05/2011',
 '06/06/2011',
 '06/07/2011',
 '06/08/2011',
 '06/09/2011',
 '06/10/2011',
 '06/12/2011',
 '07/01/2011',
 '07/03/2011',
 '07/04/2011',
 '07/05/2011',
 '07/06/2011',
 '07/07/2011',
 '07/08/2011',
 '07/10/2011',
 '07/11/2011',
 '07/12/2011',
 '08/01/2011',
 '08/02/2011',
 '08/03/2011',
 '08/04/2011',
 '08/05/2011',
 '08/07/2011',
 '08/08/2011',
 '08/09/2011',
 '08/10/2011',
 '08/11/2011',
 '08/12/2011',
 '09/01/2011',
 '09/02/2011',
 '09/04/2011',
 '09/05/2011',
 '09/06/2011',
 '09/07/2011',
 '09/08/2011',
 '09/09/2011',
 '09/11/2011',
 '09/12/2011',
 '1/13/2011',
 '1/14/2011',
 '1/16/2011',
 '1/17/2011',
 '1/18/2011',
 '1/19/2011',
 '1/20/2011',
 '1/21/2011',
 '1/23/2011',
 '1/24/2011',
 '1/25/2011',
 '1/26/2011',
 '1/27/2011',
 '1/28/2011',
 '1/30/2011',
 '1/31/2011',
 '10/02/2011',
 '10/03/2011',
 '10/04/2011',
 '10/05/2011',
 '10/06/2011',
 '10/07/2011',
 '10/09/2011',
 '10/10/2011',
 '10/11/2011',
 '10/12/2011',
 '10/13/2011',
 '10/14/2011',
 '10/16/2011',
 '10/17/2011',
 '10/18/2011',
 '10/19/2011',
 '10/20/2011',
 '10/21/2011',
 '10/23/2011',
 '10/24/2011',
 '10/25/2011',
 '10/26/2011',
 '10/27/2011',
 '10/28/2011',
 '10/30/2011',
 '10/31/2011',
 '11/01/2011',
 '11/02/2011',
 '11/03/2011',
 '11/04/2011',
 '11/06/2011',
 '11/07/2011',
 '11/08/2011',
 '11/09/2011',
 '11/10/2011',
 '11/11/2011',
 '11/13/2011',
 '11/14/2011',
 '11/15/2011',
 '11/16/2011',
 '11/17/2011',
 '11/18/2011',
 '11/20/2011',
 '11/21/2011',
 '11/22/2011',
 '11/23/2011',
 '11/24/2011',
 '11/25/2011',
 '11/27/2011',
 '11/28/2011',
 '11/29/2011',
 '11/30/2011',
 '12/01/2010',
 '12/01/2011',
 '12/02/2010',
 '12/02/2011',
 '12/03/2010',
 '12/04/2011',
 '12/05/2010',
 '12/05/2011',
 '12/06/2010',
 '12/06/2011',
 '12/07/2010',
 '12/07/2011',
 '12/08/2010',
 '12/08/2011',
 '12/09/2010',
 '12/09/2011',
 '12/10/2010',
 '12/12/2010',
 '12/13/2010',
 '12/14/2010',
 '12/15/2010',
 '12/16/2010',
 '12/17/2010',
 '12/19/2010',
 '12/20/2010',
 '12/21/2010',
 '12/22/2010',
 '12/23/2010',
 '2/13/2011',
 '2/14/2011',
 '2/15/2011',
 '2/16/2011',
 '2/17/2011',
 '2/18/2011',
 '2/20/2011',
 '2/21/2011',
 '2/22/2011',
 '2/23/2011',
 '2/24/2011',
 '2/25/2011',
 '2/27/2011',
 '2/28/2011',
 '3/13/2011',
 '3/14/2011',
 '3/15/2011',
 '3/16/2011',
 '3/17/2011',
 '3/18/2011',
 '3/20/2011',
 '3/21/2011',
 '3/22/2011',
 '3/23/2011',
 '3/24/2011',
 '3/25/2011',
 '3/27/2011',
 '3/28/2011',
 '3/29/2011',
 '3/30/2011',
 '3/31/2011',
 '4/13/2011',
 '4/14/2011',
 '4/15/2011',
 '4/17/2011',
 '4/18/2011',
 '4/19/2011',
 '4/20/2011',
 '4/21/2011',
 '4/26/2011',
 '4/27/2011',
 '4/28/2011',
 '5/13/2011',
 '5/15/2011',
 '5/16/2011',
 '5/17/2011',
 '5/18/2011',
 '5/19/2011',
 '5/20/2011',
 '5/22/2011',
 '5/23/2011',
 '5/24/2011',
 '5/25/2011',
 '5/26/2011',
 '5/27/2011',
 '5/29/2011',
 '5/31/2011',
 '6/13/2011',
 '6/14/2011',
 '6/15/2011',
 '6/16/2011',
 '6/17/2011',
 '6/19/2011',
 '6/20/2011',
 '6/21/2011',
 '6/22/2011',
 '6/23/2011',
 '6/24/2011',
 '6/26/2011',
 '6/27/2011',
 '6/28/2011',
 '6/29/2011',
 '6/30/2011',
 '7/13/2011',
 '7/14/2011',
 '7/15/2011',
 '7/17/2011',
 '7/18/2011',
 '7/19/2011',
 '7/20/2011',
 '7/21/2011',
 '7/22/2011',
 '7/24/2011',
 '7/25/2011',
 '7/26/2011',
 '7/27/2011',
 '7/28/2011',
 '7/29/2011',
 '7/31/2011',
 '8/14/2011',
 '8/15/2011',
 '8/16/2011',
 '8/17/2011',
 '8/18/2011',
 '8/19/2011',
 '8/21/2011',
 '8/22/2011',
 '8/23/2011',
 '8/24/2011',
 '8/25/2011',
 '8/26/2011',
 '8/28/2011',
 '8/30/2011',
 '8/31/2011',
 '9/13/2011',
 '9/14/2011',
 '9/15/2011',
 '9/16/2011',
 '9/18/2011',
 '9/19/2011',
 '9/20/2011',
 '9/21/2011',
 '9/22/2011',
 '9/23/2011',
 '9/25/2011',
 '9/26/2011',
 '9/27/2011',
 '9/28/2011',
 '9/29/2011',
 '9/30/2011'}

In [ ]:
set(data_test_nonclean['day'])

{'01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31'}

### แปลงวัน

In [ ]:
x=[]
for i in range(1,32):
  x.append(i)
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

In [ ]:
data_test0 = data_test_nonclean.replace(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10','11',
                                         '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
                                         '23', '24', '25', '26', '27', '28', '29', '30', '31'],x)

<ipython-input-24-211ff669797f>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_test0 = data_test_nonclean.replace(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10','11',

In [ ]:
data_test_nonclean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,01,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,01,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010

In [ ]:
data_test0.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,1,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,1,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010

### แปลงเดือน

In [ ]:
set(data_test0['month'])

{1,
 '1',
 10,
 11,
 12,
 2,
 '2',
 3,
 '3',
 4,
 '4',
 5,
 '5',
 6,
 '6',
 7,
 '7',
 8,
 '8',
 9,
 '9'}

In [ ]:
data_test = data_test0.replace(to_replace=["1", "2",'3','4','5','6','7','8','9'],value=[1,2,3,4,5,6,7,8,9])

<ipython-input-28-9808b4c818b5>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_test = data_test0.replace(to_replace=["1", "2",'3','4','5','6','7','8','9'],value=[1,2,3,4,5,6,7,8,9])

In [ ]:
data_test.isnull().any()

InvoiceNo      False
StockCode      False
Description     True
Quantity       False
InvoiceDate    False
UnitPrice      False
CustomerID      True
Country        False
date           False
day            False
month          False
year           False
dtype: bool

In [ ]:
data_test_nonclean[data_test_nonclean['month']=='01']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
42481,539993,22386,JUMBO BAG PINK POLKADOT,10,01/04/2011 10:00,1.95,13313.0,United Kingdom,01/04/2011,04,01,2011
42482,539993,21499,BLUE POLKADOT WRAP,25,01/04/2011 10:00,0.42,13313.0,United Kingdom,01/04/2011,04,01,2011
42483,539993,21498,RED RETROSPOT WRAP,25,01/04/2011 10:00,0.42,13313.0,United Kingdom,01/04/2011,04,01,2011
42484,539993,22379,RECYCLING BAG RETROSPOT,5,01/04/2011 10:00,2.10,13313.0,United Kingdom,01/04/2011,04,01,2011
42485,539993,20718,RED RETROSPOT SHOPPER BAG,10,01/04/2011 10:00,1.25,13313.0,United Kingdom,01/04/2011,04,01,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
55385,540992,21912,VINTAGE SNAKES & LADDERS,2,01/12/2011 16:57,3.75,17364.0,United Kingdom,01/12/2011,12,01,2011
55386,540992,51008,AFGHAN SLIPPER SOCK PAIR,10,01/12/2011 16:57,3.45,17364.0,United Kingdom,01/12/2011,12,01,2011
55387,540992,21508,VINTAGE KID DOLLY CARD,12,01/12/2011 16:57,0.42,17364.0,United Kingdom,01/12/2011,12,01,2011
55388,540992,22716,CARD CIRCUS PARADE,12,01/12/2011 16:57,0.42,17364.0,United Kingdom,01/12/2011,12,01,2011
55389,540992,22983,CARD BILLBOARD FONT,12,01/12/2011 16:57,0.42,17364.0,United Kingdom,01/12/2011,12,01,2011

In [ ]:
data_test[data_test['month']==1]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
42481,539993,22386,JUMBO BAG PINK POLKADOT,10,01/04/2011 10:00,1.95,13313.0,United Kingdom,01/04/2011,4,1,2011
42482,539993,21499,BLUE POLKADOT WRAP,25,01/04/2011 10:00,0.42,13313.0,United Kingdom,01/04/2011,4,1,2011
42483,539993,21498,RED RETROSPOT WRAP,25,01/04/2011 10:00,0.42,13313.0,United Kingdom,01/04/2011,4,1,2011
42484,539993,22379,RECYCLING BAG RETROSPOT,5,01/04/2011 10:00,2.10,13313.0,United Kingdom,01/04/2011,4,1,2011
42485,539993,20718,RED RETROSPOT SHOPPER BAG,10,01/04/2011 10:00,1.25,13313.0,United Kingdom,01/04/2011,4,1,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
77623,542745,22138,BAKING SET 9 PIECE RETROSPOT,13,1/31/2011 16:47,4.95,15881.0,United Kingdom,1/31/2011,31,1,2011
77624,542746,21034,REX CASH+CARRY JUMBO SHOPPER,2,1/31/2011 16:48,0.95,15881.0,United Kingdom,1/31/2011,31,1,2011
77625,C542748,22969,HOMEMADE JAM SCENTED CANDLES,-12,1/31/2011 16:53,1.45,15881.0,United Kingdom,1/31/2011,31,1,2011
77626,C542753,22649,STRAWBERRY FAIRY CAKE TEAPOT,-1,1/31/2011 16:57,4.95,15881.0,United Kingdom,1/31/2011,31,1,2011
77627,542759,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,1/31/2011 16:59,4.95,15881.0,United Kingdom,1/31/2011,31,1,2011

In [ ]:
data_test

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,1,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,1,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France,12/09/2011,9,12,2011
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France,12/09/2011,9,12,2011
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France,12/09/2011,9,12,2011

### เเบ่งทวีป

In [ ]:
set(data['Country'])

{'Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EIRE',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'RSA',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified'}

In [ ]:
# สร้าง dictionary สำหรับ mapping ประเทศไปยังทวีป
continent_mapping = {
    "Australia": "Oceania",
    "Austria": "Europe",
    "Bahrain": "Asia",
    "Belgium": "Europe",
    "Brazil": "South America",
    "Canada": "North America",
    "Channel Islands": "Europe",
    "Cyprus": "Asia",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "EIRE": "Europe",
    "European Community": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hong Kong": "Asia",
    "Iceland": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Japan": "Asia",
    "Lebanon": "Asia",
    "Lithuania": "Europe",
    "Malta": "Europe",
    "Netherlands": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "RSA": "Africa",
    "Saudi Arabia": "Asia",
    "Singapore": "Asia",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "USA": "North America",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "Unspecified": "Unspecified"
}
data_test['Continent'] = data_test['Country'].map(continent_mapping)

In [ ]:
data_test

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year,Continent
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,1,12,2010,Europe
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010,Europe
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,1,12,2010,Europe
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010,Europe
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France,12/09/2011,9,12,2011,Europe
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France,12/09/2011,9,12,2011,Europe
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011,Europe
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011,Europe
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France,12/09/2011,9,12,2011,Europe

## Code สำหรับหาชื่อสินค้า จาก Column "Description"

In [ ]:
def finditem(x,y) :
  L=set(data[(data['StockCode']==x)|(data['StockCode']==y)]['Description'])
  return L

In [ ]:
def finditems(x, y='', z='', w='') :
  I =set(data[(data['StockCode']==x)|(data['StockCode']==y)|(data['StockCode']==z)|(data['StockCode']==w)]['Description'])
  return I

### จัดกลุ่มตาม CustomerID

In [ ]:
customer_data = data_test.groupby('CustomerID')['StockCode'].apply(list)
customer_data

CustomerID
12346.0                                       [23166, 23166]
12347.0    [85116, 22375, 71477, 22492, 22771, 22772, 227...
12348.0    [84992, 22951, 84991, 84991, 21213, 21213, 226...
12349.0    [23112, 23460, 21564, 21411, 21563, 22131, 221...
12350.0    [21908, 22412, 79066K, 79191C, 22348, 84086C, ...
                                 ...
18280.0    [82484, 22180, 22467, 22725, 22727, 22495, 223...
18281.0    [22037, 22716, 22028, 23007, 23008, 23209, 22467]
18282.0    [21270, 23187, 23295, 22089, 21108, 21109, 224...
18283.0    [22356, 20726, 22384, 22386, 20717, 20718, 850...
18287.0    [22755, 22754, 22753, 22756, 22758, 22757, 227...
Name: StockCode, Length: 4372, dtype: object